import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/app/globals.css'
import Header from '@components/Header'
import SessionGuard from '@/hooks/session'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Expense Tracker',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Header />
                <SessionGuard />

                <div className=''>{children}</div>

                <div
                    className='
          flex 
          flex-col
          items-center 
          align-middle 
          gap-15
          w-100%
          h-15
        '
                >
                    <p>Emilia Päivärinta | ©2025</p>
                </div>
            </body>
        </html>
    )
}
